### ISSUE TITLE
Do you have to unbind the resizer if the dom element is eventually destroyed?

### ISSUE THREAD

**Issue by sferoze** [jcubic/jquery.resize#1]
Hello,

I attached a resizer to certain dom elements that end up getting destroyed. Will garbage collection take care of that or do I have to unbind it before the element is destroyed?

Also there is a mistake in the special event for resize fn. in the teardown fn, the removeEventListener takes 2 params but you only specified one.

**Comment by jcubic** [comment]
Not sure how jQuery works, if they fix issue that may cause memory leak in IE (not sure which version), because that the same issue. In IE you need to remove event Listener on element before you remove element. I can check the source code for jQuery to see if events are destroyed when element is removed. Because in jQuery resize AFAIK the ResizeObserver will not be removed (unless it work the same by default remove element remove resizer). As for iframe based listener (non-Chrome browsers) it's probably will garbage collect everything, unless you're in IE.

Just in case it's better to just use `element.off('resize').remove();` to be sure to not create Memory leaks.
